version: "1.0"
info:
  model: int-scaffold
packages:
- name: Siqa_Rima_Git_1108Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_rima_git_1108.integrations:SIQAAdapterFlow
  packages:
  - name: Siqa_Rima_Git_1108Project
    version: "1.0"
- serviceName: project.kvv_2404_fedtest_5a626de41e9147bcbeffc99933067bec_export.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:TestDBConn
  packages:
  - name: pkg_5a626de41e9147bcbeffc99933067bec_exported
    version: "1.0"
